import { test, type Page } from '@playwright/test';
import { answer, NOW } from './fixtures';

/**
 * The screenshots the documentation shows, taken from the real application.
 *
 * Not a test: nothing here asserts. It exists so the images in the README are
 * reproducible — regenerated by a command rather than cropped by hand from
 * somebody's install, which is how documentation ends up showing a version
 * nobody runs any more and data nobody may see.
 *
 * The API is stubbed from the same fixtures the layout suite uses, so this
 * needs the dev server and nothing else: no database, no queue, no platform
 * credential. What is rendered is the real UI over invented data.
 *
 *   npm run screenshots -w @repo/front
 */

const SHOTS = [
  { name: 'overview', path: '/dashboard/acme-platform', ready: '.board, .gauges, .stream' },
  { name: 'dora', path: '/dora/acme-platform', ready: '.metric-card, table' },
  { name: 'dora-metric', path: '/dora/acme-platform/lead_time', ready: '.page-head' },
  { name: 'deployments', path: '/deployments/acme-platform', ready: 'table, .card-list' },
  { name: 'changelogs', path: '/changelogs/acme-platform', ready: '.page-head' },
];

async function stubApi(page: Page) {
  await page.route('**/api/**', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify(answer(route.request().url())),
    });
  });
}

// Wide enough to show a table as a table, and twice the pixels so the images
// stay readable where a browser scales them down.
test.use({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2, colorScheme: 'light' });

for (const shot of SHOTS) {
  test(`screenshot: ${shot.name}`, async ({ page }) => {
    await stubApi(page);
    // Pinned to the instant the fixtures describe: without it the images say
    // "366d ago" where the application would say "8m ago".
    await page.clock.setFixedTime(new Date(NOW));
    await page.goto(shot.path);
    await page.waitForSelector(shot.ready, { timeout: 15_000 });
    // Charts and counters animate on mount; the image is taken once they have
    // settled, or half a sparkline gets published.
    await page.waitForTimeout(1_200);
    await page.screenshot({ path: `../docs/images/${shot.name}.png` });
  });
}
